version: '3.8'
services:
  api:
    build: .
    container_name: tb_debug_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - API_SECRET=badsecret
    volumes:
      - ./app:/app/app
